version: '3'

services:
  db:
    image: postgres:9.6
    hostname: ccw-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.9-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis/data


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200



volumes:
  db-data:
  redis-data:
  elasticsearch-data: