
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["CCW_DATABASE_DEV_DB"]%>
  username: <%= ENV["CCW_DATABASE_DEV_USER"]%>
  password: <%= ENV["CCW_DATABASE_DEV_PASSWORD"]%>
  host:     <%= ENV["CCW_DATABASE_DEV_HOST"]%>

test:
  <<: *default
  database: <%= ENV["CCW_DATABASE_TEST_DB"]%>
  username: <%= ENV["CCW_DATABASE_TEST_USER"]%>
  password: <%= ENV["CCW_DATABASE_TEST_PASSWORD"]%>
  host:     <%= ENV["CCW_DATABASE_TEST_HOST"]%>

production:
  <<: *default
  database: <%= ENV["CCW_DATABASE_PRODUCT_DB"]%>
  username: <%= ENV["CCW_DATABASE_PRODUCT_USER"]%>
  password: <%= ENV["CCW_DATABASE_PRODUCT_PASSWORD"]%>
  host:     <%= ENV["CCW_DATABASE_PRODUCT_HOST"]%>


demo:
  <<: *default
  database: <%= ENV["CCW_DATABASE_DEMO_DB"]%>
  username: <%= ENV["CCW_DATABASE_DEMO_USER"]%>
  password: <%= ENV["CCW_DATABASE_DEMO_PASSWORD"]%>
  host:     <%= ENV["CCW_DATABASE_DEMO_HOST"]%>
