development:
  allowed_origins:
    - '*'
  secret_key_base: <%= ENV.fetch("SECRET_TOKEN") %>


production:
  allowed_origins:
    - '*'
  secret_key_base: <%= ENV.fetch("SECRET_TOKEN") %>

demo:
  allowed_origins:
    - '*'
  secret_key_base: <%= ENV.fetch("SECRET_TOKEN") %>

test:
  allowed_origins:
    - '*'
  secret_key_base: <%= ENV.fetch("SECRET_TOKEN") %>
